AWSTemplateFormatVersion: '2010-09-09'
Description: "This template will deploy this job."

Resources:
    RuleSchedule:
        Type: AWS::Events::Rule
        Properties:
            ScheduleExpression: cron(0/30 * * * ? *)
            State: ENABLED
            Targets:
                - Arn: 
                    Ref: NotificationTopic
                  Id: qilinSechedule

    QilinSnsPolicy:
        Type: AWS::SNS::TopicPolicy
        Properties: 
            PolicyDocument: 
                Statement:
                    -
                        Effect: Allow
                        Principal: '*'
                        Action: 
                            - sns:Publish
                            - sns:Subscribe
                        Resource: '*'
            Topics: 
                - Ref: NotificationTopic
                
    NotificationTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: QilinNotificationTopic
    
    NotificationQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: QilinNotificationQueue
    
    EmailSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: phonylou@qq.com
            Protocol: email
            TopicArn: !Ref NotificationTopic
    
    QueueSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: 
                Fn::GetAtt: 
                    - NotificationQueue
                    - Arn
            Protocol: sqs
            TopicArn: !Ref NotificationTopic
    
    QilinSqsPolicy:
        Type: AWS::SQS::QueuePolicy
        Properties: 
            PolicyDocument: 
                Statement:
                    -
                        Effect: Allow
                        Principal: '*'
                        Action: 
                            - sqs:SendMessage
                            - sqs:ReceiveMessage
                        Resource: '*'
            Queues: 
                - Ref: NotificationQueue