AWSTemplateFormatVersion: '2010-09-09'
Description: "This template will deploy this job."

Resources:
    RuleSchedule:
        Type: AWS::Events::Rule
        Properties:
            ScheduleExpression: cron(0/30 * * * ? *)
            State: ENABLED
            Targets:
                - Arn: 
                    Ref: NotificationTopic
                  Id: qilinSechedule

    QilinSnsPolicy:
        Type: AWS::SNS::TopicPolicy
        Properties: 
            PolicyDocument: 
                Statement:
                    -
                        Effect: Allow
                        Principal: '*'
                        Action: 
                            - sns:Publish
                            - sns:Subscribe
                        Resource: '*'
            Topics: 
                - Ref: NotificationTopic
                
    NotificationTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: QilinNotificationTopic
    
    NotificationQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: QilinNotificationQueue
            MessageRetentionPeriod: 604800
            VisibilityTimeout: 300
    
    EmailSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: phonylou@qq.com
            Protocol: email
            TopicArn: !Ref NotificationTopic
    
    QueueSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Endpoint: 
                Fn::GetAtt: 
                    - NotificationQueue
                    - Arn
            Protocol: sqs
            TopicArn: !Ref NotificationTopic
    
    QilinSqsPolicy:
        Type: AWS::SQS::QueuePolicy
        Properties: 
            PolicyDocument: 
                Statement:
                    -
                        Effect: Allow
                        Principal: '*'
                        Action: 
                            - sqs:SendMessage
                            - sqs:ReceiveMessage
                            - sqs:ReceiveMessage
                            - sqs:DeleteMessage
                            - sqs:GetQueueAttributes
                        Resource: '*'
            Queues: 
                - Ref: NotificationQueue
    
    # QilinEventFunction:
    #     Type: AWS::Lambda::Function
    #     Properties:
    #         Handler: com.serverless.Handler
    #         FunctionName: qilin-event-feeder
    #         Role: arn:aws:iam::494526681395:role/for-aws-training-2
    #         Code:
    #             S3Bucket: qilin-event-feeder
    #             S3Key: qilin-event-feeder.jar
    #         Runtime: java8
    #         Timeout: 30
    #         MemorySize: 512

    # QilinEventSourceMapping:
    #     Type: AWS::Lambda::EventSourceMapping
    #     Properties:
    #         BatchSize: 10
    #         Enabled: true
    #         EventSourceArn: !GetAtt NotificationQueue.Arn
    #         FunctionName: !GetAtt QilinEventFunction.Arn

    # QilinInvolkFunPermission:
    #     Type: AWS::Lambda::Permission
    #     Properties:
    #         FunctionName: 
    #             Fn::GetAtt:
    #                 - QilinEventFunction
    #                 - Arn
    #         Action: lambda:InvokeFunction
    #         Principal: events.amazonaws.com
    #         SourceArn:
    #             Fn::GetAtt:
    #             - NotificationQueue
    #             - Arn